apiVersion: v1
kind: Service
metadata:
  annotations:
    com.example.description: Postgres Database
  creationTimestamp: null
  labels:
    service: db
  name: db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    service: db
status:
  loadBalancer: {}
